sudo: false

language: php

php:
    - 5.4

env:
    - WP_VERSION=latest WP_MULTISITE=0
    - WP_VERSION=latest WP_MULTISITE=1

matrix:
    include:
    - php: "5.3"
      env: WP_VERSION=3.9
    - php: "5.2"
      env: WP_VERSION=4.1

before_script:
    - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION 

script: phpunit && phpunit --group ajax
