sudo: false

language: php

php:
    - 7.0

env:
    - WP_VERSION=latest WP_MULTISITE=0
    - WP_VERSION=latest WP_MULTISITE=1

matrix:
    include:
    - php: "5.4"
      env: WP_VERSION=4.0
    - php: "5.4"
      env: WP_VERSION=4.3
    - php: "5.2"
      env: WP_VERSION=4.5

before_script:
    - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION 
    - |
      if [[ ${TRAVIS_PHP_VERSION:0:2} == "7." ]]; then
        composer global require "phpunit/phpunit=5.7.*"
      elif [[ ${TRAVIS_PHP_VERSION:0:3} != "5.2" ]]; then
        composer global require "phpunit/phpunit=4.8.*"
      fi

script: phpunit && phpunit --group ajax
