language: php

php:
    - 5.2
    - 5.3
    - 5.4

env:
    - WP_VERSION=latest WP_MULTISITE=0
    - WP_VERSION=latest WP_MULTISITE=1
    - WP_VERSION=3.8 WP_MULTISITE=0
    - WP_VERSION=3.8 WP_MULTISITE=1

before_script:
    - mysql -u root --password=root -e "CREATE DATABASE IF NOT EXISTS wpt_test"
    - mysql -u root --password=root -e "GRANT ALL PRIVILEGES ON wpt_test.* TO wp@localhost IDENTIFIED BY 'wp';"
    - bash bin/install-wp-tests.sh wpt_test wp 'wp' localhost $WP_VERSION 

script: phpunit
