sudo: false

language: php

php:
    - 5.4

env:
    - WP_VERSION=3.8.1 WP_MULTISITE=0

before_script:
    - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION 

script: phpunit && phpunit --group ajax
